all:
	gcc src/mm1.c -o bin/mm1 -O0 -lpapi -static
	gcc src/mm2.c -o bin/mm2 -O0 -lpapi -static
	gcc src/mm3.c -o bin/mm3 -O0 -lpapi -static
	gcc src/mm4.c -o bin/mm4 -O0 -lpapi -static
	gcc src/mm5.c -o bin/mm5 -O0 -lpapi -static
	gcc src/mm6.c -o bin/mm6 -O0 -lpapi -static
	gcc src/mm7.c -o bin/mm7 -O0 -lpapi -static
	gcc src/mm8.c -o bin/mm8 -O0 -lpapi -static
	gcc src/mm9.c -o bin/mm9 -O0 -lpapi -static
	gcc src/mm10.c -o bin/mm10 -O0 -lpapi -static
	
run:
	./bin/mm1 0 >> wynik0
	./bin/mm2 0 >> wynik0
	./bin/mm3 0 >> wynik0
	./bin/mm4 0 >> wynik0
	./bin/mm5 0 >> wynik0
	./bin/mm6 0 >> wynik0
	./bin/mm7 0 >> wynik0
	./bin/mm8 0 >> wynik0
	./bin/mm9 0 >> wynik0
	./bin/mm10 0 >> wynik0
	./bin/mm1 1 >> wynik1
	./bin/mm2 1 >> wynik1
	./bin/mm3 1 >> wynik1
	./bin/mm4 1 >> wynik1
	./bin/mm5 1 >> wynik1
	./bin/mm6 1 >> wynik1
	./bin/mm7 1 >> wynik1
	./bin/mm8 1 >> wynik1
	./bin/mm9 1 >> wynik1
	./bin/mm10 1 >> wynik1
	./bin/mm1 2 >> wynik2
	./bin/mm2 2 >> wynik2
	./bin/mm3 2 >> wynik2
	./bin/mm4 2 >> wynik2
	./bin/mm5 2 >> wynik2
	./bin/mm6 2 >> wynik2
	./bin/mm7 2 >> wynik2
	./bin/mm8 2 >> wynik2
	./bin/mm9 2 >> wynik2
	./bin/mm10 2 >> wynik2
	./bin/mm1 3 >> wynik3
	./bin/mm2 3 >> wynik3
	./bin/mm3 3 >> wynik3
	./bin/mm4 3 >> wynik3
	./bin/mm5 3 >> wynik3
	./bin/mm6 3 >> wynik3
	./bin/mm7 3 >> wynik3
	./bin/mm8 3 >> wynik3
	./bin/mm9 3 >> wynik3
	./bin/mm10 3 >> wynik3
	./bin/mm1 4 >> wynik4
	./bin/mm2 4 >> wynik4
	./bin/mm3 4 >> wynik4
	./bin/mm4 4 >> wynik4
	./bin/mm5 4 >> wynik4
	./bin/mm6 4 >> wynik4
	./bin/mm7 4 >> wynik4
	./bin/mm8 4 >> wynik4
	./bin/mm9 4 >> wynik4
	./bin/mm10 4 >> wynik4
